// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package payload

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SignInClient is the client API for SignIn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignInClient interface {
	Auth(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
}

type signInClient struct {
	cc grpc.ClientConnInterface
}

func NewSignInClient(cc grpc.ClientConnInterface) SignInClient {
	return &signInClient{cc}
}

var signInAuthStreamDesc = &grpc.StreamDesc{
	StreamName: "Auth",
}

func (c *signInClient) Auth(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/payload.SignIn/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignInService is the service API for SignIn service.
// Fields should be assigned to their respective handler implementations only before
// RegisterSignInService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type SignInService struct {
	Auth func(context.Context, *SignInRequest) (*SignInResponse, error)
}

func (s *SignInService) auth(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/payload.SignIn/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Auth(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterSignInService registers a service implementation with a gRPC server.
func RegisterSignInService(s grpc.ServiceRegistrar, srv *SignInService) {
	srvCopy := *srv
	if srvCopy.Auth == nil {
		srvCopy.Auth = func(context.Context, *SignInRequest) (*SignInResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "payload.SignIn",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Auth",
				Handler:    srvCopy.auth,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "payload.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewSignInService creates a new SignInService containing the
// implemented methods of the SignIn service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewSignInService(s interface{}) *SignInService {
	ns := &SignInService{}
	if h, ok := s.(interface {
		Auth(context.Context, *SignInRequest) (*SignInResponse, error)
	}); ok {
		ns.Auth = h.Auth
	}
	return ns
}

// UnstableSignInService is the service API for SignIn service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableSignInService interface {
	Auth(context.Context, *SignInRequest) (*SignInResponse, error)
}
